import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  // Keep cache/version skew keys stable for a given release. The cryptographic
  // prerender secret remains randomly generated by vinext for every build.
  generateBuildId: async () => "governdiff-reviewer-0.1.0",
};

export default nextConfig;
